{
  "filename": "hsb_Steel Alone.mcr",
  "status": "completed",
  "total_tokens": 41408,
  "processing_time": 198.3228964805603,
  "passes": {
    "1": {
      "success": true,
      "data": {
        "header": {
          "type": null,
          "numBeamsReq": null,
          "keywords": [],
          "majorVersion": null,
          "minorVersion": null,
          "dxaOut": null,
          "implInsert": null
        },
        "description": "",
        "versionHistory": [
          {
            "version": "1.0",
            "date": "03.07.2008",
            "author": "Alberto Jena (aj@hsb-cad.com)",
            "changes": "Release Version"
          },
          {
            "version": "1.2",
            "date": "09.03.2009",
            "author": "",
            "changes": "Remove the display of the body."
          },
          {
            "version": "1.3",
            "date": "29.10.2010",
            "author": "",
            "changes": "Add the plate and the TSL to the group of the Beam"
          }
        ],
        "settingsFiles": [],
        "dependencies": [
          "hsb-SubAssembly"
        ]
      },
      "tokens_used": 5697,
      "error": null
    },
    "2": {
      "success": true,
      "data": {
        "usageEnvironment": {
          "primarySpace": "ModelSpace",
          "supportsPaperSpace": false,
          "isShopDrawingScript": false,
          "isMultipageScript": false,
          "detectionEvidence": "The script uses getBeam() and getPoint() for insertion, creates 3D geometry (Body, Cut, Drill), and instantiates new elements with dbCreate(). It contains no #Type E declaration, _Entity[] arguments, or sd_ prefixes. While it contains commented-out code referencing showInShopDraw, the active script operates by generating physical objects and linking them via SubAssembly logic."
        },
        "prerequisites": {
          "requiredEntities": [
            "GenBeam"
          ],
          "minimumBeams": 1,
          "requiredSpace": "3D Model Space",
          "requiredSettings": [
            "hsb-SubAssembly"
          ]
        }
      },
      "tokens_used": 5747,
      "error": null
    },
    "3": {
      "success": true,
      "data": {
        "commandLine": {
          "insertionFlow": [
            {
              "step": 1,
              "function": "getBeam",
              "promptOriginal": "Select Male Beam",
              "condition": "_bOnInsert",
              "required": true
            },
            {
              "step": 2,
              "function": "getPoint",
              "promptOriginal": "Please select a point on the side of the beam where you need the Plate",
              "condition": "_bOnInsert",
              "required": true
            }
          ],
          "keywordOptions": []
        },
        "dialogs": [],
        "opmProperties": [
          {
            "index": 0,
            "variable": "dPlateWidth",
            "type": "PropDouble",
            "displayName": "Plate Width",
            "defaultValue": "U(80)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 1,
            "variable": "dPlateHeight",
            "type": "PropDouble",
            "displayName": "Plate Height",
            "defaultValue": "U(150)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 2,
            "variable": "dPlateThickness",
            "type": "PropDouble",
            "displayName": "Plate Thickness",
            "defaultValue": "U(15)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 0,
            "variable": "sShape",
            "type": "PropString",
            "displayName": "Location Top",
            "defaultValue": "Straight",
            "inputType": "dropdown",
            "options": [
              "Straight",
              "L Shape"
            ],
            "category": null,
            "description": null
          },
          {
            "index": 0,
            "variable": "nQty",
            "type": "PropInt",
            "displayName": "Holes per Side",
            "defaultValue": 0,
            "inputType": "dropdown",
            "options": [
              0,
              1,
              2
            ],
            "category": null,
            "description": null
          },
          {
            "index": 3,
            "variable": "dDrillTopOffset",
            "type": "PropDouble",
            "displayName": "Drill Top Offset",
            "defaultValue": "U(32)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 4,
            "variable": "dDrillSideOffset",
            "type": "PropDouble",
            "displayName": "Drill Side Offset",
            "defaultValue": "U(32)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 5,
            "variable": "dDrillDiam",
            "type": "PropDouble",
            "displayName": "Drill Diameter",
            "defaultValue": "U(16)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 1,
            "variable": "sName",
            "type": "PropString",
            "displayName": "Plate Model",
            "defaultValue": "Plate",
            "inputType": "text",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 1,
            "variable": "nColor",
            "type": "PropInt",
            "displayName": "Color",
            "defaultValue": -1,
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          }
        ],
        "contextMenu": [],
        "settingsFiles": []
      },
      "tokens_used": 7717,
      "error": null
    },
    "4": {
      "success": true,
      "data": {
        "scriptPurpose": {
          "summary": "Generates a steel connection plate attached to the side of a timber beam, creating a void for the plate thickness and optionally adding bolt holes.",
          "category": "Hardware/Connection",
          "typicalUseCase": "Used when a steel gusset or flitch plate needs to be attached to the side of a timber beam to transfer loads or connect members."
        },
        "parameters": [
          {
            "name": "dPlateWidth",
            "technicalDefault": "U(80)",
            "businessMeaning": "The horizontal width of the steel plate (along the beam's Y-axis).",
            "validRange": "50mm - 300mm",
            "unit": "mm",
            "affectsOutput": "Resizes the plate geometry along the beam's local width."
          },
          {
            "name": "dPlateHeight",
            "technicalDefault": "U(150)",
            "businessMeaning": "The vertical height of the steel plate (along the beam's Z-axis).",
            "validRange": "50mm - 600mm",
            "unit": "mm",
            "affectsOutput": "Resizes the plate geometry along the beam's local height."
          },
          {
            "name": "dPlateThickness",
            "technicalDefault": "U(15)",
            "businessMeaning": "The depth of the steel plate (protrusion from the beam).",
            "validRange": "5mm - 30mm",
            "unit": "mm",
            "affectsOutput": "Determines the depth of the cut void in the timber beam and the thickness of the generated steel body."
          },
          {
            "name": "sShape",
            "technicalDefault": "\"Straight\"",
            "businessMeaning": "The geometric profile of the plate relative to the beam corner.",
            "validRange": "Straight, L Shape",
            "unit": "Enum",
            "affectsOutput": "'Straight' creates a single rectangular block. 'L Shape' wraps the plate around the corner, combining two plates into an L-profile."
          },
          {
            "name": "nQty",
            "technicalDefault": "0",
            "businessMeaning": "Number of bolt holes per side to be drilled into the plate.",
            "validRange": "0, 1, or 2",
            "unit": "count",
            "affectsOutput": "If > 0, adds drill operations to the plate. 1 adds one set of holes, 2 adds a second set symmetrically."
          },
          {
            "name": "dDrillTopOffset",
            "technicalDefault": "U(32)",
            "businessMeaning": "Edge distance from the top of the plate to the center of the bolt hole.",
            "validRange": "20mm - 50mm",
            "unit": "mm",
            "affectsOutput": "Adjusts the vertical position of the drill holes."
          },
          {
            "name": "dDrillSideOffset",
            "technicalDefault": "U(32)",
            "businessMeaning": "Edge distance from the side of the plate to the center of the bolt hole.",
            "validRange": "20mm - 50mm",
            "unit": "mm",
            "affectsOutput": "Adjusts the horizontal position of the drill holes."
          },
          {
            "name": "dDrillDiam",
            "technicalDefault": "U(16)",
            "businessMeaning": "Diameter of the bolt holes.",
            "validRange": "12mm - 24mm",
            "unit": "mm",
            "affectsOutput": "Changes the size of the drilled holes."
          },
          {
            "name": "sName",
            "technicalDefault": "\"Plate\"",
            "businessMeaning": "The model name or label assigned to the plate for BOM/export.",
            "validRange": "Any alphanumeric string",
            "unit": "text",
            "affectsOutput": "Updates the entity name property; no geometric change."
          },
          {
            "name": "nColor",
            "technicalDefault": "-1",
            "businessMeaning": "The CAD color index used to display the plate.",
            "validRange": "0-255 (AutoCAD Index), -1 (ByLayer)",
            "unit": "index",
            "affectsOutput": "Changes the visual color of the generated beam and TSL markers."
          }
        ],
        "parameterDependencies": [
          {
            "trigger": "sShape changes to 'L Shape'",
            "effect": "Modifies the reference geometry used to calculate drill positions (using Beam Height/Width as the bounding box instead of the Plate dimensions).",
            "cascade": [
              "dDrillTopOffset",
              "dDrillSideOffset"
            ]
          },
          {
            "trigger": "nQty is set to 0",
            "effect": "Disables drill generation; Offset and Diameter parameters have no visual effect.",
            "cascade": [
              "dDrillTopOffset",
              "dDrillSideOffset",
              "dDrillDiam"
            ]
          }
        ],
        "outputEntities": [
          {
            "type": "Beam",
            "description": "A new 3D body representing the steel plate.",
            "appliedTo": "Model Space (grouped with the selected host beam)."
          },
          {
            "type": "Cut",
            "description": "A void removed from the host beam to accommodate the plate thickness.",
            "appliedTo": "The selected Male Beam (_Beam0)."
          },
          {
            "type": "Drill",
            "description": "Through holes for bolts.",
            "appliedTo": "The generated Steel Plate."
          }
        ]
      },
      "tokens_used": 7644,
      "error": null
    },
    "5": {
      "success": true,
      "data": {
        "workflowDiagram": [
          "User launches script (hsb_Steel Alone.mcr).",
          "System checks if script is being inserted (_bOnInsert).",
          "If inserted, show Properties Dialog once (showDialogOnce).",
          "Prompt user to Select Male Beam (getBeam).",
          "Prompt user to select point on beam side for Plate (getPoint).",
          "Calculate insertion point relative to beam center (Line::closestPointTo).",
          "Apply Cut tool to Male Beam to create void for plate thickness.",
          "Determine plate geometry based on sShape (Straight vs L Shape).",
          "Generate Body (bd) representing the steel plate.",
          "Create new Beam entity (bmPlate) from the Body.",
          "Set Color, Name, and SubLabel for the new Beam.",
          "Add new Beam and TSL instance to the host beam's Group.",
          "Check number of holes (nQty).",
          "If nQty > 0, calculate drill points based on shape and offsets.",
          "Apply Drill tools to the new Beam and Body.",
          "Draw visual markers (cross lines) at plate center.",
          "Ensure SubAssembly TSL exists on host beam (create if missing).",
          "Add new Plate Beam to the SubAssembly map."
        ],
        "conditionalBranches": [
          {
            "condition": "User sets sShape property",
            "path1": {
              "name": "Straight",
              "steps": [
                "Use _Pt0 as plate origin.",
                "Create single rectangular Body (Width x Height).",
                "Calculate drill positions relative to Plate Width/Height."
              ]
            },
            "path2": {
              "name": "L Shape",
              "steps": [
                "Adjust origin to beam bottom corner (-vy*dWBm*0.5 - vz*dHBm*0.5).",
                "Create primary Body.",
                "Create secondary Body (swapped Width/Height) and add to primary.",
                "Calculate drill positions using dPlateHeight for both local axes."
              ]
            }
          },
          {
            "condition": "User sets nQty (Holes per Side)",
            "path1": {
              "name": "0 Holes",
              "steps": [
                "Skip drill generation logic."
              ]
            },
            "path2": {
              "name": "1 Hole",
              "steps": [
                "Calculate first set of drill coordinates (ptDrill1, ptDrill2).",
                "Create Drill tools and apply to Plate."
              ]
            },
            "path3": {
              "name": "2 Holes",
              "steps": [
                "Calculate first set of drill coordinates.",
                "Calculate second set of drill coordinates (mirrored/offset).",
                "Create Drill tools for all points and apply to Plate."
              ]
            }
          }
        ],
        "validationRules": [
          {
            "check": "Beam selection",
            "errorMessage": "Implicitly handled by getBeam() failure to select.",
            "recovery": "User must select a valid GenBeam."
          },
          {
            "check": "Point selection",
            "errorMessage": "Implicitly handled by getPoint() failure.",
            "recovery": "User must select a valid point on the beam side."
          },
          {
            "check": "Existing 'bm' entity in Map",
            "errorMessage": "None (handled automatically).",
            "recovery": "Script automatically erases existing plate entity before regeneration."
          }
        ],
        "postInsertionActions": [
          {
            "action": "Change Plate Dimensions",
            "how": "OPM (Properties Palette) - Edit dPlateWidth, dPlateHeight, dPlateThickness",
            "effect": "Regenerates the steel plate body and updates the void in the host beam."
          },
          {
            "action": "Change Plate Shape",
            "how": "OPM - Edit sShape (Straight / L Shape)",
            "effect": "Switches geometry between a single plate and an L-wrapped plate; recalculates drill positions."
          },
          {
            "action": "Modify Drilling Pattern",
            "how": "OPM - Edit nQty, dDrillTopOffset, dDrillSideOffset, dDrillDiam",
            "effect": "Adds, removes, or relocates bolt holes on the generated plate."
          },
          {
            "action": "Update Visuals",
            "how": "OPM - Edit nColor, sName",
            "effect": "Changes display color and renames the plate for BOM/Export."
          },
          {
            "action": "Delete Script",
            "how": "Erase TSL Instance",
            "effect": "The steel plate is removed, but the void (Cut) in the host beam remains unless handled by external logic."
          }
        ]
      },
      "tokens_used": 8362,
      "error": null
    },
    "6": {
      "success": true,
      "data": {
        "markdown": "# hsb_Steel Alone.mcr\n\n## Overview\nThis script generates a steel connection plate attached to the side of a timber beam. It automatically creates a void (cut) in the timber beam to accommodate the plate thickness and optionally adds bolt holes.\n\n## Usage Environment\n| Space | Supported | Notes |\n|-------|-----------|-------|\n| Model Space | Yes | This is the primary environment for the script. |\n| Paper Space | No | Not supported in layout views. |\n| Shop Drawing | No | Does not generate 2D shop drawing details directly. |\n\n## Prerequisites\n- **Required Entities**: At least one Timber Beam (GenBeam).\n- **Minimum Beam Count**: 1\n- **Required Settings/Dependencies**: The script requires `hsb-SubAssembly` to be loaded in the environment to function correctly.\n\n## Usage Steps\n\n### Step 1: Launch Script\nCommand: `TSLINSERT` â†’ Select `hsb_Steel Alone.mcr` from the file list.\n\n### Step 2: Select Host Beam\n```\nCommand Line: Select Male Beam\nAction: Click on the timber beam you want to attach the steel plate to.\n```\n\n### Step 3: Define Plate Location\n```\nCommand Line: Please select a point on the side of the beam where you need the Plate\nAction: Click on the face of the selected beam where the steel plate should be positioned.\n```\n\n## Properties Panel Parameters\n\nOnce inserted, select the script instance in the drawing to view and edit these parameters in the Properties Palette (OPM).\n\n| Parameter | Type | Default | Description |\n|-----------|------|---------|-------------|\n| Plate Width | Number | 80 mm | The horizontal width of the steel plate. |\n| Plate Height | Number | 150 mm | The vertical height of the steel plate. |\n| Plate Thickness | Number | 15 mm | The depth of the plate (affects the size of the cut in the beam). |\n| Location Top | Dropdown | Straight | Determines shape: **Straight** (single plate) or **L Shape** (wraps around the beam corner). |\n| Holes per Side | Dropdown | 0 | Number of bolt holes to drill in the plate (0, 1, or 2). |\n| Drill Top Offset | Number | 32 mm | Distance from the top edge of the plate to the center of the hole. |\n| Drill Side Offset | Number | 32 mm | Distance from the side edge of the plate to the center of the hole. |\n| Drill Diameter | Number | 16 mm | Diameter of the bolt holes. |\n| Plate Model | Text | Plate | Name/Label assigned to the plate for lists or exports. |\n| Color | Number | -1 | CAD Color index (-1 = ByLayer). |\n\n## Right-Click Menu Options\n\nThis script does not add specific custom commands to the right-click context menu. All modifications should be made via the **Properties Palette**.\n\n## Settings Files\n- **Filename**: `hsb-SubAssembly` (Dependency)\n- **Location**: hsbCAD Environment / TSL Folder\n- **Purpose**: Ensures the generated steel plate is correctly grouped and associated with the host timber beam.\n\n## Tips\n- **L Shape Connections**: Select \"L Shape\" in the *Location Top* property if you need the plate to wrap around the top or side corner of the beam for greater surface area.\n- **Modification**: You can adjust dimensions, hole counts, and offsets at any time by selecting the script instance and updating values in the Properties Palette. The geometry will regenerate automatically.\n- **Deletion Warning**: If you erase (delete) this script instance from the drawing, the steel plate will be removed. However, the void (cut) in the host timber beam will remain. You may need to repair the timber beam geometry manually if you delete the script.\n\n## FAQ\n- **Q: Why is there a hole/cut in my timber beam?**\n  - A: The script automatically generates a void in the host beam matching the *Plate Thickness* parameter. This represents the space occupied by the steel plate in the assembly.\n- **Q: How do I add bolt holes after insertion?**\n  - A: Select the script, open the Properties Palette, and change *Holes per Side* from **0** to **1** or **2**.\n- **Q: Can I move the plate to a different side of the beam?**\n  - A: It is usually easier to delete the script instance and re-run it, selecting the new point on the desired side, rather than trying to adjust coordinates manually."
      },
      "tokens_used": 6241,
      "error": null
    }
  }
}