{
  "filename": "hsbStirnblatt.mcr",
  "status": "completed",
  "total_tokens": 26271,
  "processing_time": 247.85138702392578,
  "passes": {
    "1": {
      "success": true,
      "data": {
        "header": {
          "type": null,
          "numBeamsReq": null,
          "keywords": null,
          "majorVersion": null,
          "minorVersion": null,
          "dxaOut": null,
          "implInsert": null
        },
        "description": null,
        "versionHistory": [
          {
            "version": "1.2",
            "date": "02jul13",
            "author": "th@hsbCAD.de",
            "changes": "beam stretch added"
          },
          {
            "version": "1.1",
            "date": "27jun13",
            "author": "th@hsbCAD.de",
            "changes": "export flag set"
          },
          {
            "version": "1.0",
            "date": "15dec11",
            "author": "th@hsbCAD.de",
            "changes": "initial"
          }
        ],
        "settingsFiles": [],
        "dependencies": []
      },
      "tokens_used": 2831,
      "error": null
    },
    "2": {
      "success": true,
      "data": {
        "usageEnvironment": {
          "primarySpace": "ModelSpace",
          "supportsPaperSpace": false,
          "isShopDrawingScript": false,
          "isMultipageScript": false,
          "detectionEvidence": "The script uses interactive command-line inputs getBeam() and getPoint() within the _bOnInsert block. It creates 3D geometry (House) and adds tools to a _Beam object. There are no references to _Viewport, _Entity arrays, #Type E, or ShopDrawing specific API calls."
        },
        "prerequisites": {
          "requiredEntities": [
            "GenBeam"
          ],
          "minimumBeams": 1,
          "requiredSpace": "Model Space",
          "requiredSettings": []
        }
      },
      "tokens_used": 2731,
      "error": null
    },
    "3": {
      "success": true,
      "data": {
        "commandLine": {
          "insertionFlow": [
            {
              "step": 1,
              "function": "getBeam",
              "promptOriginal": null,
              "condition": "_bOnInsert",
              "required": true
            },
            {
              "step": 2,
              "function": "getPoint",
              "promptOriginal": null,
              "condition": "_bOnInsert",
              "required": true
            }
          ],
          "keywordOptions": []
        },
        "dialogs": [
          {
            "type": "showDialog",
            "trigger": "Insertion if _kExecuteKey is empty",
            "title": null,
            "dataSource": "Script Properties",
            "features": {
              "searchable": false,
              "multiSelect": false
            }
          }
        ],
        "opmProperties": [
          {
            "index": 0,
            "variable": "dY",
            "type": "PropDouble",
            "displayName": "|Width|",
            "defaultValue": "U(80)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 1,
            "variable": "dZ",
            "type": "PropDouble",
            "displayName": "|Height|",
            "defaultValue": "U(80)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 2,
            "variable": "dX",
            "type": "PropDouble",
            "displayName": "|Depth|",
            "defaultValue": "U(9)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 3,
            "variable": "dOffsetY",
            "type": "PropDouble",
            "displayName": "|Offset| Y",
            "defaultValue": "U(0)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 4,
            "variable": "dOffsetZ",
            "type": "PropDouble",
            "displayName": "|Offset| Z",
            "defaultValue": "U(0)",
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 5,
            "variable": "dGap",
            "type": "PropDouble",
            "displayName": "|Gap|",
            "defaultValue": 0,
            "inputType": "number",
            "options": [],
            "category": null,
            "description": null
          },
          {
            "index": 0,
            "variable": "sRelief",
            "type": "PropString",
            "displayName": "|Relief|",
            "defaultValue": "|not rounded|",
            "inputType": "dropdown",
            "options": [
              "|not rounded|",
              "|rounded|",
              "|relief|",
              "|rounded with small diameter|",
              "|relief with small diameter|",
              "|rounded|"
            ],
            "category": null,
            "description": null
          }
        ],
        "contextMenu": [],
        "settingsFiles": []
      },
      "tokens_used": 3440,
      "error": null
    },
    "4": {
      "success": true,
      "data": {
        "scriptPurpose": {
          "summary": "Creates a recess (pocket) and a square cut at the end of a beam to accommodate a Stirnblatt (front/end plate).",
          "category": "Connection/Machining",
          "typicalUseCase": "Preparing a beam end to receive a metal or wood connection plate by milling a pocket of specific depth and clearance."
        },
        "parameters": [
          {
            "name": "dY",
            "technicalDefault": "U(80)",
            "businessMeaning": "The width of the end plate (Stirnblatt).",
            "validRange": "40 - 400 mm",
            "unit": "mm",
            "affectsOutput": "Determines the horizontal size of the pocket cut into the beam end (plus any gap)."
          },
          {
            "name": "dZ",
            "technicalDefault": "U(80)",
            "businessMeaning": "The height of the end plate.",
            "validRange": "40 - 400 mm",
            "unit": "mm",
            "affectsOutput": "Determines the vertical size of the pocket cut into the beam end (plus any gap)."
          },
          {
            "name": "dX",
            "technicalDefault": "U(9)",
            "businessMeaning": "The thickness of the end plate / Depth of the pocket.",
            "validRange": "5 - 30 mm",
            "unit": "mm",
            "affectsOutput": "Determines how deep the machine cuts into the beam from the end face."
          },
          {
            "name": "dOffsetY",
            "technicalDefault": "U(0)",
            "businessMeaning": "Lateral offset of the plate center relative to the insertion point.",
            "validRange": "-200 to 200 mm",
            "unit": "mm",
            "affectsOutput": "Moves the pocket left or right along the beam width axis."
          },
          {
            "name": "dOffsetZ",
            "technicalDefault": "U(0)",
            "businessMeaning": "Vertical offset of the plate center relative to the insertion point.",
            "validRange": "-200 to 200 mm",
            "unit": "mm",
            "affectsOutput": "Moves the pocket up or down along the beam height axis."
          },
          {
            "name": "dGap",
            "technicalDefault": "0",
            "businessMeaning": "Clearance allowance around the plate.",
            "validRange": "0 - 5 mm",
            "unit": "mm",
            "affectsOutput": "Increases the width and height of the cut pocket by twice this value (Gap + Plate + Gap) to ensure the physical plate fits easily."
          },
          {
            "name": "sRelief",
            "technicalDefault": "|not rounded|",
            "businessMeaning": "The corner geometry of the pocket (Chamfered, Rounded, or Sharp).",
            "validRange": "Selection List",
            "unit": "N/A",
            "affectsOutput": "Changes the milling toolpath at the corners of the pocket (e.g., creating a chamfer for stress relief or aesthetic reasons)."
          }
        ],
        "parameterDependencies": [
          {
            "trigger": "dGap is modified",
            "effect": "The actual milling dimensions for Width and Height are calculated as Plate Dimension + (2 * dGap).",
            "cascade": [
              "dY",
              "dZ"
            ]
          }
        ],
        "outputEntities": [
          {
            "type": "Cut",
            "description": "Squares off the end of the beam at the insertion point.",
            "appliedTo": "Selected Beam (_Beam[0])"
          },
          {
            "type": "House (Pocket/Milling)",
            "description": "Subtractive volume representing the recess for the plate. Includes corner relief settings.",
            "appliedTo": "Selected Beam (_Beam[0])"
          }
        ]
      },
      "tokens_used": 6146,
      "error": null
    },
    "5": {
      "success": true,
      "data": {
        "workflowDiagram": [
          "1. Script execution initiated (Insertion or Recalculation).",
          "2. Check safety condition: Is insertCycleCount > 1?",
          "3. [Insertion Mode] Determine input source: Is _kExecuteKey empty?",
          "4. [Insertion Mode] Branch: Show Properties Dialog OR Load Catalog Properties.",
          "5. [Insertion Mode] User Command Line Prompt: Select Beam (getBeam).",
          "6. [Insertion Mode] User Command Line Prompt: Select Insertion Point (getPoint).",
          "7. [Insertion Mode] Terminate insertion phase (return).",
          "8. [Calculation Phase] Apply 'Cut' tool to the beam end at the insertion point.",
          "9. [Calculation Phase] Calculate Reference Point using Y and Z offsets.",
          "10. [Calculation Phase] Create 'House' (Pocket) with Width/Height adjusted by Gap, Depth, and Relief settings.",
          "11. [Calculation Phase] Apply 'House' tool to the beam.",
          "12. [Display] Draw preview line indicating pocket depth."
        ],
        "conditionalBranches": [
          {
            "condition": "insertCycleCount > 1",
            "path1": {
              "name": "Safety Exit",
              "steps": [
                "Erase the current script instance.",
                "Return immediately (prevents duplicate execution on drag/copy)."
              ]
            },
            "path2": {
              "name": "Normal Execution",
              "steps": [
                "Proceed to Property Input check."
              ]
            }
          },
          {
            "condition": "_kExecuteKey is empty (Catalog check)",
            "path1": {
              "name": "Manual Input",
              "steps": [
                "Execute showDialog() to open properties palette for user entry."
              ]
            },
            "path2": {
              "name": "Catalog Load",
              "steps": [
                "Execute setPropValuesFromCatalog(_kExecuteKey) to load preset values."
              ]
            }
          }
        ],
        "validationRules": [
          {
            "check": "Beam Selection",
            "errorMessage": "User cancels beam selection or selects invalid entity.",
            "recovery": "Script insertion is aborted by the system. User must restart the command."
          },
          {
            "check": "Insertion Point",
            "errorMessage": "User does not provide a point.",
            "recovery": "Script insertion is aborted by the system. User must restart the command."
          }
        ],
        "postInsertionActions": [
          {
            "action": "Modify Parameters",
            "how": "OPM (Object Properties Palette)",
            "effect": "Updates Width (dY), Height (dZ), Depth (dX), Offsets (dOffsetY/Z), Gap (dGap), or Relief type. The pocket geometry recalculates immediately."
          },
          {
            "action": "Move Connection Point",
            "how": "Grip Edit (Drag the insertion point grip)",
            "effect": "Relocates the location of the cut and pocket along the beam length and face."
          },
          {
            "action": "Modify Parent Beam",
            "how": "Move or Stretch the beam using standard AutoCAD/hsbCAD tools",
            "effect": "The Stirnblatt tools (Cut and House) update their position relative to the beam's local coordinate system."
          }
        ]
      },
      "tokens_used": 5427,
      "error": null
    },
    "6": {
      "success": true,
      "data": {
        "markdown": "# hsbStirnblatt.mcr\n\n## Overview\nThis script automates the creation of a pocket and a square cut at the end of a timber beam to accommodate a front connection plate (Stirnblatt). It allows for precise configuration of the plate dimensions, positioning offsets, and corner relief geometry.\n\n## Usage Environment\n| Space | Supported | Notes |\n|-------|-----------|-------|\n| Model Space | Yes | This script must be run in 3D Model Space. |\n| Paper Space | No | Not applicable for 2D layouts. |\n| Shop Drawing | No | This is a detailing/manufacturing script, not a drawing generator. |\n\n## Prerequisites\n- **Required Entities**: One `GenBeam` (General Beam) must exist in the drawing.\n- **Minimum Beam Count**: 1\n- **Required Settings Files**: None\n\n## Usage Steps\n\n### Step 1: Launch Script\nCommand: `TSLINSERT` â†’ Select `hsbStirnblatt.mcr` from the file dialog.\n\n### Step 2: Configure Properties\nIf you are running the script without a specific catalog entry, a Properties Dialog will appear immediately.\n- Set the desired Width, Height, and Depth for the pocket.\n- Configure any necessary Offsets or Relief options.\n- Click **OK** to proceed.\n\n### Step 3: Select Beam\n```\nCommand Line: Select beam:\nAction: Click on the timber beam you wish to modify.\n```\n*Note: If you cancel this selection, the script will stop.*\n\n### Step 4: Define Insertion Point\n```\nCommand Line: Give insertion point:\nAction: Click on the beam's face or end where you want the center (or offset location) of the plate to be positioned.\n```\nThe script will now calculate the geometry and apply the cut and pocket to the beam.\n\n## Properties Panel Parameters\n\n| Parameter | Type | Default | Description |\n|-----------|------|---------|-------------|\n| **Width** (dY) | Number | 80 mm | The horizontal width of the plate pocket. |\n| **Height** (dZ) | Number | 80 mm | The vertical height of the plate pocket. |\n| **Depth** (dX) | Number | 9 mm | The depth of the cut into the beam (thickness of the plate). |\n| **Offset** Y (dOffsetY) | Number | 0 mm | Moves the pocket center left or right from the insertion point. |\n| **Offset** Z (dOffsetZ) | Number | 0 mm | Moves the pocket center up or down from the insertion point. |\n| **Gap** (dGap) | Number | 0 mm | Adds clearance around the plate (Total Width/Height = Dimension + 2 * Gap). |\n| **Relief** (sRelief) | Dropdown | not rounded | Defines the corner geometry of the pocket (e.g., sharp, rounded, or relieved). |\n\n## Right-Click Menu Options\n\n| Menu Item | Description |\n|-----------|-------------|\n| *None* | No custom context menu items are defined for this script. Standard AutoCAD/hsbCAD options apply. |\n\n## Settings Files\n- **Filename**: None\n- **Location**: N/A\n- **Purpose**: This script uses internal properties and does not require external XML settings files.\n\n## Tips\n- **Adjusting Tolerances**: If the physical plate fits too tightly, increase the **Gap** property in the palette rather than manually adjusting the Width/Height.\n- **Stress Relief**: For structural connections or to prevent wood cracking, change the **Relief** property to \"rounded\" or \"relief\" to chamfer the internal corners of the pocket.\n- **Quick Modifications**: After insertion, select the beam and open the **Properties** palette (Ctrl+1) to find the hsbStirnblatt entry. You can drag sliders or type new values to resize the pocket in real-time.\n- **Moving the Connection**: Use the **Grip Edit** feature (select the beam, click the square grip at the insertion point) to slide the plate along the beam face.\n\n## FAQ\n- **Q: How do I change the plate size after I have already placed it?**\n  A: Select the beam in the drawing. Open the Properties palette (OPM). Scroll down to the section named after this script (or look for the variables dY, dZ, dX) and change the values.\n- **Q: Why is my pocket not centered on the beam face?**\n  A: Check the **Offset** Y and Z values. If they are not 0, the pocket will be shifted from your clicked insertion point.\n- **Q: What does the \"Depth\" property do?**\n  A: It controls how far the machine cuts into the timber from the end face. This should match the thickness of the metal/wood plate you are inserting."
      },
      "tokens_used": 5696,
      "error": null
    }
  }
}